#!/bin/bash

if ! [ -d "$1" ]; then
	echo 'Script only accepts on argument, the folder path of the docker compose project' >&2
	exit 1
fi

pushd "$1"

if ! [ -f 'docker-compose.yaml' ]; then
	echo 'No docker-compose file found' >&2
	popd
	exit 1
fi

# Stop the container
docker-compose stop

# Pull the new image
docker-compose pull

# Restart and recreate the container
docker-compose up --force-recreate --build -d

# Delete unused image
docker image prune -f

popd

# Note: All data which is not stored persistently in docker volumes will be lost by upgrading the container!

